/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.labs.epapi;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.solace.labs.epapi.wrapper.EventPortalClient;
import com.solace.labs.epapi.wrapper.SchemaToPojo;
import com.solace.labs.epapi.wrapper.SchemaToPojo.Builder;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        
    	
    	
    	EventPortalClient.INSTANCE.setToken("eyJhbGciOiJSUzI1NiIsImtpZCI6Im1hYXNfcHJvZF8yMDIwMDMyNiIsInR5cCI6IkpXVCJ9.eyJvcmciOiJzb2xhY2VjdG8iLCJvcmdUeXBlIjoiRU5URVJQUklTRSIsInN1YiI6IjY3dHI4dGt0eHgiLCJwZXJtaXNzaW9ucyI6IkFBQUFBQUFBQUFBQVF3QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFJQUFBTFA3L2c1Y2ZCUm9BQU1BQUNRPT0iLCJhcGlUb2tlbklkIjoiOTI3Y3Z1MzQ2M3IiLCJpc3MiOiJTb2xhY2UgQ29ycG9yYXRpb24iLCJpYXQiOjE2NTg0NTE0ODh9.kJ3ppLqldtYz8Y3VLSqD6D0-ZyWM5f_nmRDjKUdxQYvenzKFkHS_8JI_vSPSnHVHPdfoOR6eT6QAjurjzzqkwgWnH0E3zae4MJSi1rp2PbPkBXOjv1wOvzyc4_i-Da23tY1cS3oobI6bc4LqQsKtXPClR9SSG_CEA3DiHFvd1UYwly8TS7ZKpyo5y1eygYWhRKaHYJUa2T1Pxxv9NcCuP5Gu_uTB1O7zV19v6mtvKZUzVSo1YCk7QMwrm7OgNLulQ5h2R-AD5Rq82YhRVhphldaduVql9_6EXGzv-SjQkKb5D_xUHYDzZdDuMbYk4aM2k_IAJlrsrGXd2rpancjUsw");
    	EventPortalClient.INSTANCE.load();
    	
        
        SchemaToPojo.Builder builder = new Builder().setSchemaVersionId("fkfgxsm5h8x")
        		.setBasePackageName("com.solace.aaron.model")
        		.setFilePath("src/main/java");
        System.out.println(builder);
        assertTrue("builder.build() should return 'true'", builder.build());
    }
}
