/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package community.solace.ep;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.concurrent.Executors;

import org.junit.BeforeClass;
import org.junit.Test;

import community.solace.ep.wrapper.EventPortalWrapper;

public class AysyncApiFetchTest {
	
	private static final EventPortalWrapper EPW = EventPortalWrapper.INSTANCE;
	
	@BeforeClass public static void load() {
    	Properties p = new Properties();
    	try {
			p.load(new FileInputStream("token.properties"));
			EventPortalWrapper.INSTANCE.setToken(p.getProperty("token"));
	    	EventPortalWrapper.INSTANCE.loadAll(Executors.newFixedThreadPool(10));
		} catch (IOException e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}

    @Test public void testSomeLibraryMethod() {
    	
    	System.out.println(EPW.getAsyncApiForAppVerId("u39ey35iel6", true));
    	
    	
    	
    	
    }
}
