/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package community.solace.ep;

import static org.junit.Assert.assertTrue;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;

import org.junit.BeforeClass;
import org.junit.Test;

import community.solace.ep.wrapper.EventPortalWrapper;
import community.solace.ep.wrapper.SchemaToPojo;
import community.solace.ep.wrapper.SchemaToPojo.Builder;

public class CodegenTest {
	
	@BeforeClass public static void load() {
    	Properties p = new Properties();
    	try {
			p.load(new FileInputStream("token.properties"));
			EventPortalWrapper.INSTANCE.setToken(p.getProperty("token"));
	    	EventPortalWrapper.INSTANCE.loadAll();
		} catch (IOException e) {
			e.printStackTrace();
			throw new RuntimeException(e);
		}
	}

    @Test public void testSomeLibraryMethod() {
        SchemaToPojo.Builder builder = new Builder().setSchemaVersionId("uvkail7pnsb")
        		.setBasePackageName("com.solace.aaron.model")
        		.setFilePath("src/main/java");
        System.out.println(builder);
        assertTrue("builder.build() should return 'true'", builder.build());
    }
}
